### ISSUE TITLE
Grab pictures

### ISSUE THREAD

**Issue by rickdeneer** [denniedegroot/com.ring#23] opened 2019-06-28 07:25 UTC
I'd like to have snapshots on my mobile phone when there is someone in front of my door. Is it possible to have this feature in this app in combination with Homey?

**Comment by mruiter** [comment] 2019-06-28 08:37
Only when Athom becomes a ring partner. Else there Will be no access to the pictures since ring blocked this earlier this year. 

Just e-mail Athom on support@athom.com that you would like them to become ring partner so this is possible 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment] 2019-06-28 09:02
It seems they just found out a few hours ago on how the pictures are being made available after the ring change a few months ago

https://github.com/tchellomello/python-ring-doorbell/issues/124

On the bottom they are now able to grab the pictures

**Comment by rodroz** [comment] 2019-07-18 16:20
Well that's good, but it seems like the Homey project is idle unfortunately. My hope is that someone with the proper skills to implement the changes can continue.

**Comment by denniedegroot** [comment] 2019-09-03 19:47
Duplicate of #18

**Closed by denniedegroot** 2019-09-03 19:47 UTC
