### ISSUE TITLE
No more devices showing up

### ISSUE THREAD

**Issue by BBEHannes** [denniedegroot/com.ring#37] opened 2019-12-20 13:41 UTC
Since a day or so there are no more devices showing up in the app and the existing ones disappeared. Tried reinstalling but without luck.

**Comment by tccflash** [comment] 2019-12-21 11:51
Same here... I read than ring makes changes in there api... Would be nice if the creator of the ring app have a look about this! :+1:

**Comment by mruiter** [comment] 2019-12-21 14:56
The existing also went away ???
No problem here see attached picture 

But by any chance did you activate multi factor authentication after the promotion mail that ring send out last week ?

Mfa does not work with the app and will disconnect it when you enable it 



Verstuurd vanaf mijn iPhone

**Comment by BBEHannes** [comment] 2019-12-21 15:09
I had it activated (MFA) before. Now it is disabled entirely but it doesn’t find any devices anymore and times out.

**Comment by ralfh73** [comment] 2019-12-21 15:21
Same issue here:
reinstalled the app, but couldn't add any devices any more.

**Comment by tccflash** [comment] 2019-12-21 16:21
I don't activate mfa, but no devices found. I reinstalled the app too... But same issue.

**Comment by daneedk** [comment] 2019-12-21 16:23
My observations, with a Ring Pro:

- Device still available in Homey (Did not remove the device or app)
- The `The generic alarm turned on` and `The motion alarm turned on` flow cards are no longer triggered
- The `Grab current snapshot` flow card still functions.

(For reference, the *Since a day or so* from the topic starter most likely coincides with the 'hacking' attempt of Ring accounts, which Ring reported in an email to its users urging to enable multi factor authentication)

**Comment by jahnkenneth** [comment] 2019-12-22 13:33
Same here, cannot add new devices... It just times out.

**Comment by FrankSmeets01** [comment] 2019-12-24 15:22
I see that a fix for this issue is prepared as per V2.1.3. Any idea when this version will be released? Will it be a Beta again? Or will there be a new stable version (eg 2.0.6) that can be installed via the regular Homey App store?

**Comment by denniedegroot** [comment] 2019-12-24 16:26
@FrankSmeets01 I have no clue. I am waiting on Athom for approval.

**Comment by Fire69** [comment] 2019-12-27 22:30
I installed 3.1.4 today and at first sight it seemed like it was working (battery level was updated correctly).
But I tested motion and right this evening and it's not working.
Removed/added the device also, didn't solve the problem.

**Comment by Fire69** [comment] 2019-12-28 12:22
Update:
I saw on the forum that a user had the same problem but that it 'magically' started working today.
So I tested also and indeed, it's working now.
I'm guessing the problem was with Ring instead of your app...

**Comment by daneedk** [comment] 2019-12-28 14:23
I can confirm today the `The generic alarm turned on` and `The motion alarm turned on` flow cards spontaneously started to work again! (On earlier cli installed 2.1.4)

**Comment by ralfh73** [comment] 2019-12-28 16:07
Just installed version 2.1.4
doorbell found, flow with generic alarm and snapshot works.

**Comment by mortenkols** [comment] 2019-12-29 14:35
Where can i download 2.1.4?

**Comment by Fire69** [comment] 2019-12-29 15:51
Euhm... https://github.com/denniedegroot/com.ring ? :)

**Comment by mruiter** [comment] 2019-12-29 16:57
I get the confusion, but app.json still tells you version 2.1.3 but peeps refer to that as 2.1.4 

Verstuurd vanaf mijn iPhone

**Comment by Fire69** [comment] 2019-12-29 17:09
app.json correctly has 2.1.4 in it, but it's the comments for several commits that still have 2.1.3

**Comment by mortenkols** [comment] 2019-12-29 19:50
In the homey store its only 2.0.5 available. How can i install 2.1.4?

**Comment by Fire69** [comment] 2019-12-29 19:54
Wait for Athom to approve the new version, or else: https://community.athom.com/t/how-to-cli-install-method/198

**Comment by denniedegroot** [comment] 2020-01-07 18:35
Released in the appstore.

**Closed by denniedegroot** 2020-01-07 18:35 UTC
