### ISSUE TITLE
Ring spotlight cam

### ISSUE THREAD

**Issue by wmmudde** [denniedegroot/com.ring#19] opened 2019-03-17 09:34 UTC
Hello,

Is it possible to create support and the correct icon for Ring Spotlight cam?
And Maybe ADD function to trigger lights and alarm? Thanks in advance.

**Comment by denniedegroot** [comment] 2019-03-17 18:45
Please see issue #10 

Duplicate of #10

**Closed by denniedegroot** 2019-03-17 18:45 UTC
